import Header from "@/components/Header";
import "./globals.css";
import { IBM_Plex_Mono } from "next/font/google";
import Footer from "@/components/Footer";
import Wagmi from "@/context/Wagmi";
import { BuyProvider } from "@/context/Buy";
import BuyModal from "@/components/Buy";

const inter = IBM_Plex_Mono({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Wagmi>
      <BuyProvider>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            <BuyModal />
            {children}
            <Footer />
          </body>
        </html>
      </BuyProvider>
    </Wagmi>
  );
}
